=== Musimatix/musimatix-backend/verse-rates-rest/src/main/resources/schema/frontend.songs.response.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Full songs' info",
  "self": {
    "vendor": "com.musimatix",
    "name": "songs_response",
    "format": "jsonschema",
    "version": "1-0-0"
  },
  "definitions": {
    "rows": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": false
    },
    "tag": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Tag's id in database"
        },
        "name": {
          "type": "string",
          "description": "Tag's readable name corresponded to current lang property"
        }

      }
    },
    "author": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "object": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "lang":  {
      "type": "string"
    },
    "songs": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id":  {
            "type": "integer"
          },
          "title": {
            "type": "string"
          },
          "group": {
            "type": "string"
          },
          "authors": {
            "type": "array",
            "items" : {
              "$ref": "#/definitions/author"
            },
            "minItems": 1,
            "uniqueItems": true
          },
          "rowsPlain": {
            "$ref": "#/definitions/rows",
            "description": "Song rows as a plain text"
          },
          "rowsTagged": {
            "$ref": "#/definitions/rows",
            "description": "Song rows where accented syllables are marked with {}"
          },
          "tags": {
            "type": "array",
            "items" : {
              "$ref": "#/definitions/tag"
            },
            "minItems": 1,
            "uniqueItems": true
          }
        },
        "required": ["id"],
        "additionalProperties": false
      }
    }
  },
  "required": ["object", "songs"],
  "additionalProperties": false
}

=== Musimatix/musimatix-backend/verse-rates-rest/src/main/resources/schema/frontend.songs.response.sample.json
{
  "object": "frontend.songs.response",
  "version": "1.0",
  "lang": "eng",
  "songs": [
    {
      "id": 1234,
      "group": "Chumbawamba",
      "authors": [
        {
          "id": 765,
          "name": "Duncan Bruce"
        },
        {
          "id": 987,
          "name": "Darren James Hamer"
        }
      ],
      "title": "Tubthumping",
      "rowsPlain": [
        "We'll be singing",
        "When we're winning",
        "We'll be singing",
        "I get knocked down",
        "But I get up again",
        "You're never gonna keep me down"
      ],
      "rowsTagged": [
        "We'll be {si}nging",
        "{When} we're {wi}nning",
        "We'll be singing",
        "I get {knock}ed down",
        "But I get {up} again",
        "You're never gonna keep me down"
      ],
      "tags": [
        {
          "id": 2,
          "name": "rock"
        },
        {
          "id": 11,
          "name": "moody"
        },
        {
          "id": 23,
          "name": "punk"
        }
      ]

    }
  ]
}
