=== Musimatix/musimatix-backend/verse-rates-rest/src/main/resources/schema/frontend.tags.response.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Tags list",
  "self": {
    "vendor": "com.musimatix",
    "name": "tags_response",
    "format": "jsonschema",
    "version": "1-0-0"
  },
  "type": "object",
  "properties": {
    "object": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "lang":  {
      "type": "string"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Tag's id in database"
          },
          "name": {
            "type": "string",
            "description": "Tag's readable name corresponded to current lang property"
          }
        },
        "required": ["id", "name"],
        "additionalProperties": false
      }
    }
  },
  "required": ["object", "tags"],
  "additionalProperties": false
}

=== Musimatix/musimatix-backend/verse-rates-rest/src/main/resources/schema/frontend.tags.response.sample.json
{
  "object": "frontend.tags.response",
  "version": "1.0",
  "lang": "eng",
  "tags": [
    {
      "id": 1,
      "name": "rock"
    },
    {
      "id": 2,
      "name": "funny"
    },
    {
      "id": 3,
      "name": "jazz"
    },
    {
      "id": 4,
      "name": "moody"
    },
    {
      "id": 77,
      "name": "punk"
    }
  ]
}
